version: '3.4'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ../DATA/mysql/var/lib/mysql:/var/lib/mysql
    networks:
        kloia-local:
            ipv4_address: 148.14.72.67
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--max_allowed_packet=32505856']
            
networks:
    kloia-local:
        external: true